### ISSUE TITLE
No type declaration

### ISSUE THREAD

**Issue by PhilipokTheCat** [klaviyo/klaviyo-api-node#1]
I would be really happy if you make a type declaration for your SDK, or at least '@types/klaviyo-api' package with it

**Comment by vpylypenko-klaviyo** [comment]
We appreciate the feedback and will take this idea into consideration for 2023

**Comment by thesuavehog** [comment]
100% this is needed. We can generate types from the Open API spec but much nicer to have them integrated with the SDK so we get true compile-time type checking.

**Comment by ciriousjoker** [comment]
This would be huge to speed up development.

Right now calling functions feels like trial and error. Imports aren't provided automatically, available functions aren't suggested at all.

It feels like complete trial and error to use this sdk and it's much easier to just copypaste the `fetch()` examples from the Documentation and write mini-wrappers for the needed functions manually.

#### Specific example (kind of a rant tbh):

How do you use this thing: https://developers.klaviyo.com/en/reference/get_profiles

First attempt was this, but it throws with 400.
```ts
const response = await Profiles.getProfiles({
  "fields[profile]": ["external_id"],
  filter: uid,
});
```

Second attempt:
```ts
const response = await Profiles.getProfiles({
  fields: {
    profile: ["external_id"], 
  },
  filter: uid,
});
```

Looking at the code, apparently `fields[profile]` was renamed to `fieldsProfile`? Why? On the npm page the `getProfiles()` links to the [official documentation](https://developers.klaviyo.com/en/reference/get_profiles) and since it's a "thin wrapper" I would expect it to match it exactly, like it did with [createProfile()](https://developers.klaviyo.com/en/reference/create_profile).

https://github.com/klaviyo/klaviyo-api-node/blob/e33552cbb78a7d1c89c1d417f5ba2c1cafa1a9e0/src/api/ProfilesApi.js#L281

New attempt:

```ts
const response = await Profiles.getProfiles({
  fieldsProfile: ["external_id"],
  filter: uid,
});
```

Of course that still didn't work. I tried debugging this for a bit, but trying to make sense of the mess that Babel generates is annoying and even more so unnecessary.

At this point I realized that any correlation between the npm package and the documentation is pure coincidence. On the [npm page](https://www.npmjs.com/package/klaviyo-api) I finally found the part about filtering and its seemingly random and arbitrary format of `any(prop, [a, b, ...])` that deviates from the official documentation which is just a string that you combine with the filter array.

This worked:

```ts
filter: `any(external_id,["${uid}"])`,
```

---

Now you could say that this was my incompetence for not reading the npm package's documentation after the part that said

> This SDK exactly mirrors the organization and naming convention of the above language-agnostic resources, with a few namespace changes to make it Pythonic (details in Appendix).

and instead scrolling down straight to `Installation` and the list of functions.

You'd be right, but imagine this was a Typescript package with additional js-only exports for compatibility.

Intellisense would write literally everything for you and you wouldn't even need to look at the documentation except to get a broad overview how things like Profiles and Segments are related. Everything else like parameters, return types, their explanations and possible values would all be done automatically. Even better, setting breakpoints actually helps now because when stepping into functions you see the real code and not that Babel-garbage.

**Comment by samcfinan** [comment]
Seconded on the need for types.

**Comment by a-hryshchenko** [comment]
Would love to see support for the types too

**Comment by brian-pinwheel** [comment]
Type definitions make the integration so much easier.  In fact, since I saw the library is generated via OpenAPI, you can simply change the target for the language to typescript.  This will give you types for free without having to do additional work.

If you are looking for types before this library can provide them, I recommend using the OpenAPI client generator directly on the OpenAPI spec (appears the latest spec can be found in this [repo here](https://raw.githubusercontent.com/klaviyo/openapi/main/openapi/stable.json) and target a typescript generator.  Should be pretty much the same thing as adding types to this library but you can get it in less than 5 minutes.

**Comment by ryancraigmartin** [comment]
If anyone stumbles across this, read's @brian-pinwheel's suggestion and wants to test it out. I created this [gist](https://gist.github.com/ryancraigmartin/b161b1efda765e40ce89f37dea7c4680) using the [openapi-typescript](https://github.com/drwpow/openapi-typescript) package to generate types using the [openapi spec he referenced above](https://raw.githubusercontent.com/klaviyo/openapi/main/openapi/stable.json).

**Comment by lukebars** [comment]
Having typescript in 2023 is a must.

**Comment by sagrawal31** [comment]
This is a must. I was super happy to see the node library but super disappointed to find this issue after I came here looking for TypeScript support. Would appreciate the TypeScript support.

**Comment by viktor-ku** [comment]
Same thing here about the types! Why in 2023 we are still lacking this?

**Comment by lewebsimple** [comment]
For anyone looking for an open source alternative with better type support, check out [Novu](https://novu.co/) !

**Comment by enchorb** [comment]
+1, painful using this without types

**Comment by Ian-Montgomery-Klaviyo** [comment]
To add better type support we remade the entire SDK in typescript, Check out the branch [here](https://github.com/klaviyo/klaviyo-api-node/tree/typescript-beta). It's currently a beta, so let us know if there are any changes need in either core functionality to quality of life improvements.

**Comment by Ian-Montgomery-Klaviyo** [comment]
If you wish to provide any feedback outside of a github issue, you can reach out to us [here]. (https://docs.google.com/forms/d/e/1FAIpQLSckdxPXezeY6SludpOGpJ2nNZU280tEnSwuRnEyx0XNS02zdA/viewform)

**Comment by DenisRupp** [comment]
@Ian-Montgomery-Klaviyo Could you please provide an estimate for when the non-beta version of TypeScript will be released? thanks

**Comment by Ian-Montgomery-Klaviyo** [comment]
Typescript is now in GA reflected on the `main` branch. The pre-types code now lives on `node_no_types`
