### ISSUE TITLE
Profiles API timing out on sorting DESC -created or -updated

### ISSUE THREAD

**Issue by RhysC** [klaviyo/klaviyo-api-node#76]
under the hood the call is `/api/profiles/?fields[profile]=email&page[size]=100&sort=-created` (desc created) and this seems to time out. Removing the sort and a response is fine 
This also fails on `-updated` (desc updated)
However `created` or `updated` are ok (but not really useful for many scenarios)

**Comment by cpcurtis1218** [comment]
Hi there - thank you for raising this issue.  Would you please [open a Support Ticket](https://help.klaviyo.com/hc/en-us/articles/115001002272) for this issue so that we may investigate further?  In the Support Ticket, please include:
- 6 digit Klaviyo Account ID
- Details about how the request is being made
- Details about time timeout error itself
- Is this an ongoing issue?  Or past error that is now resolved?

For reference, you can find request details in your Klaviyo account using the developer logs (https://www.klaviyo.com/developer-tools/logs).
